### ISSUE TITLE
Error when starting container: cron not found

### ISSUE THREAD

**Issue by drhaynes** [bloveless/s3-backup-restore#3]
I am getting the following error when trying to deploy as a sidecar container in a k8s pod:

```
Error: failed to start container "s3-backup": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "cron": executable file not found in $PATH: unknown
```

No output from `kubectl logs` and I'm not able to start a shell in the container, as it has failed to start.

Any ideas if I'm doing something wrong?

Config below:

```
  - name: s3-backup
    image: bloveless/s3-backup-restore:1.0.2
    volumeMounts:
      - name: wordpress-data
        mountPath: /bitnami/wordpress
    command: ["cron"]
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: backup-keys-myapp
            key: aws_access_key_id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: backup-keys-myapp
            key: aws_secret_access_key
      - name: AWS_REGION
        value: "eu-west-1"
      - name: S3_BUCKET
        value: "my-wordpress-backups"
      - name: S3_PATH
        value: "wordpress-pv-backup"
      - name: CHOWN_ENABLE
        value: "true"
      - name: CHOWN_UID
        value: "1000"
      - name: CHOWN_GID
        value: "1000"
```
